import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar/Navbar";
import Footer from "./Components/Footer/Footer";
import '@fortawesome/fontawesome-svg-core/styles.css'; 
import "./lib/fontawesome"; 

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    
    default: "Leading Bangladesh - IT solutions - Managed IT services",
    template: "%s | Leading Bangladesh ",
  },
  description: "Generated by Leading Bangladesh"
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        
        {children}
        

        <Footer></Footer>
        
        </body>
    </html>
  );
}
